<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="uml" nsURI="http://www.example.org/uml" nsPrefix="uml">
  <eClassifiers xsi:type="ecore:EClass" name="HCL">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasComp" lowerBound="1"
        upperBound="-1" eType="#//Computer" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Storage" eSuperTypes="#//Configure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasDisk" lowerBound="1"
        upperBound="-1" eType="#//Disk" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Processing" eSuperTypes="#//Configure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasL2" lowerBound="1" eType="#//L2"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasL1" lowerBound="1" eType="#//L1"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasL3" lowerBound="1" eType="#//L3"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="cores" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Display" eSuperTypes="#//Configure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagonal" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//DisplayType"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Disk">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//StorageType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="StorageType">
    <eLiterals name="SSD" literal="SSD"/>
    <eLiterals name="HDD" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L2">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="#//CacheUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L1">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="#//CacheUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="L3">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unit" lowerBound="1" eType="#//CacheUnit"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CacheUnit">
    <eLiterals name="KiB"/>
    <eLiterals name="MiB" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="DisplayType">
    <eLiterals name="HD"/>
    <eLiterals name="Full-HD" value="1"/>
    <eLiterals name="4K" value="2"/>
    <eLiterals name="5K" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Computer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasProc" lowerBound="1"
        upperBound="-1" eType="#//Processing" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasDisp" lowerBound="1"
        upperBound="-1" eType="#//Display" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="hasStor" lowerBound="1"
        upperBound="-1" eType="#//Storage" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="conf" upperBound="-1" eType="#//Configure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configure" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
